# Generated by Django 5.1.4 on 2025-01-28 12:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.FloatField()),
                ('file_type', models.CharField(max_length=100)),
                ('crypto_type', models.CharField(max_length=20)),
                ('algorithm', models.CharField(max_length=50)),
                ('metric', models.CharField(max_length=50)),
                ('visualization', models.CharField(max_length=20)),
                ('bar_type', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('estimated_time', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'File Analyses',
            },
        ),
    ]
