# Generated by Django 4.2.17 on 2025-01-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fileanalysis',
            table='analysis_fileanalysis',
        ),
    ]
