# Generated by Django 5.1.4 on 2025-02-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileanalysis',
            name='bar_type',
        ),
        migrations.RemoveField(
            model_name='fileanalysis',
            name='visualization',
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='crypto_type',
            field=models.CharField(choices=[('asymmetric', 'ASYMMETRIC'), ('symmetric', 'SYMMETRIC')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='metric',
            field=models.CharField(choices=[('filesize_time', 'FILESIZE_TIME'), ('keysize_time', 'KEYSIZE_TIME')], max_length=50),
        ),
    ]
