# Generated by Django 5.1.4 on 2025-02-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_remove_fileanalysis_bar_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileanalysis',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'File Analyses'},
        ),
        migrations.RemoveField(
            model_name='fileanalysis',
            name='metric',
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='analysis_type',
            field=models.CharField(choices=[('keysize', 'Key Size Analysis'), ('filesize', 'File Size Analysis')], default='filesize', max_length=20),
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='crypto_type',
            field=models.CharField(choices=[('symmetric', 'SYMMETRIC'), ('asymmetric', 'ASYMMETRIC'), ('hash', 'HASH')], max_length=20),
        ),
    ]
