# Generated by Django 4.2.17 on 2025-02-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_fileanalysis_table'),
        ('analysis', '0002_remove_fileanalysis_bar_type_and_more'),
    ]

    operations = [
    ]
