# Generated by Django 4.2.17 on 2025-02-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_fileanalysis_table'),
        ('analysis', '0003_alter_fileanalysis_options_and_more'),
    ]

    operations = [
    ]
